services:
  backend:
    build: ./backend
    container_name: stock-api
    restart: always
    volumes:
      - ./backend:/app
      - stock_db_data:/app/data
    networks:
      - traefik-public
      - internal
    labels:
      - "traefik.enable=true"
      # ホスト名を新しいサブドメインに変更
      - "traefik.http.routers.stock-api.rule=Host(`api-stock-check.go-pro-world.net`)"
      - "traefik.http.routers.stock-api.entrypoints=websecure"
      - "traefik.http.routers.stock-api.tls=true"
      - "traefik.http.routers.stock-api.tls.certresolver=lets-encrypt"
      - "traefik.http.services.stock-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-public"
    environment:
      - TZ=Asia/Tokyo

networks:
  internal:
    driver: bridge
  traefik-public:
    external: true

volumes:
  stock_db_data:
  